Update requirements.txt
Pre-reliance is required in the windows environment:

E:\work\CosyVoice-win>.\py311\python.exe -m pip install WeTextProcessing
WARNING: Ignoring invalid distribution ~bb (E:\work\CosyVoice-win\py311\Lib\site-packages)
Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
Collecting WeTextProcessing
  Using cached https://mirrors.aliyun.com/pypi/packages/ed/8f/c0fa549d04759fd48e27c55f8c2e69470c0228cbfba96ef3fef6a53bf383/WeTextProcessing-1.0.3-py3-none-any.whl (2.0 MB)
Collecting pynini==2.1.5 (from WeTextProcessing)
  Using cached https://mirrors.aliyun.com/pypi/packages/86/63/6a720dbdf4e7358baa2ab206a51693f9c6e83d174179a95539f501bd4a34/pynini-2.1.5.tar.gz (627 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\zcxey\AppData\Local\Temp\pip-install-efp9t96j\pynini_01e70cf7bbac4c148ff4322b3d7d49d3\setup.py", line 22, in <module>
          from Cython.Build import cythonize
      ModuleNotFoundError: No module named 'Cython'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.